### ISSUE TITLE
Proposal: Named wildcards

### ISSUE THREAD

**Issue by samueleaton** [jgaskins/nats#4]
Was thinking of ways to improve UX with NATS clients in general and I think the ability to have named parameters for wildcards would be a major win. 

These types of innovations belong on clients, not part of the core protocols. Similar to how most HTTP server frameworks allow you to map a wildcard to a variable like `/users/:user_id/posts/:post_id`.

For example, if I defined a subscription with a subject like `users.{user_id}.posts.{post_id}.>`, then the NATS client would map that to `users.*.posts.*.>` and then when publish message come in, it will do the mappings and the `NATS::Message` object would have a `NATS::Message::Params` hash property that could look like:

```crystal
{
"user_id" => "some value...",
"post_id" => "another value...",
"tail" => "a tail value from the '>' character..."
}
```

This would start setting trends for other NATS clients IMO.

**Comment by jgaskins** [comment]
I don't love the positional style, either, especially when there's more than 1-2 wildcards in a subject. I usually end up doing something like this in a lot of my subscription blocks:

```crystal
_, user_id, _, post_id, tail = msg.subject.split('.', 5)
```

I don't know what the CPU load required to parse a params hash from the subject would be, but I suspect that they didn't go that route because it would be higher than the current implementation. The NATS crew optimizes pretty aggressively for extreme scale.

So for messages that require more parameters, I've ended up using request objects in the message body gRPC-style:

```protobuf
message GetPostByUser {
  int64 user_id = 1;
  int64 post_id = 2;
}
```

And the in the subscription:

```crystal
nats.subscribe "get_post_by_user", queue_group: MY_QUEUE_GROUP do |msg|
  request = GetPostByUser.from_protobuf(msg.body)

  response = create_a_response_somehow(request)

  nats.reply msg, response.to_protobuf.to_slice
end
```

I have no idea what conventions look like in NATS here, but I suspect the lack of first-party-prescribed conventions is intentional.

**Comment by samueleaton** [comment]
>  ...I suspect that they didn't go that route...
> ...I have no idea what conventions look like in NATS here...

This wouldn't have anything to do with the core NATS team or protocols, just like how HTTP servers like Express, Sinatra, or Kemal supply this for the developer, and they don't need to worry about how other frameworks map path segments to variables. It's a layer of abstraction over the core protocols and is still compliant. The NATS server would never know what user improvements the respective clients make.

However, I think your example with the `split(char : Char, limit : Int32)` is really concise. I like it.
